version: "3.9"

services:
  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
    - mododb-data:/data/db
    ports:
    - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo_user
      - MONGO_INITDB_ROOT_PASSWORD=mongo_password

volumes:
  mododb-data: